#
# Deploys a service: busyboxes2 with two pods: busybox2a and busybox2b
# With "clusterIP:" absent " - DNS is configured and will round robbin across the pods in the service
#
#
apiVersion: v1
kind: Service
metadata:
  name: busyboxes2
  namespace: test
spec:
  selector:
    name: busyboxes2
#  clusterIP: None
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2a
  namespace: test
  labels:
    name: busyboxes2
spec:
  hostname: busybox2a
  subdomain: busy
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2b
  namespace: test
  labels:
    name: busyboxes2
spec:
  hostname: busybox2b
  subdomain: busy
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
    ports:
    - containerPort: 80
